<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Bogus" Version="35.6.5" />
    <PackageVersion Include="MarkdownSnippets.MsBuild" Version="28.4.2" />
    <PackageVersion Include="Microsoft.Sbom.Targets" Version="4.1.5" />
    <PackageVersion Include="Polyfill" Version="11.2.0" />
    <PackageVersion Include="ProjectDefaults" Version="1.0.180" />
    <PackageVersion Include="System.CodeDom" Version="10.0.11" />
    <PackageVersion Include="UnicodeInformation" Version="2.7.1" />
    <PackageVersion Include="Verify.TUnit" Version="32.0.0" />
    <PackageVersion Include="Argon" Version="0.36.0" />
    <PackageVersion Include="DiffEngine" Version="20.1.2" />
    <PackageVersion Include="EmptyFiles" Version="8.18.2" />
    <PackageVersion Include="SimpleInfoName" Version="3.2.0" />
    <PackageVersion Include="Verify" Version="32.0.0" />
    <PackageVersion Include="TUnit" Version="1.65.68" />
  </ItemGroup>
</Project>
